version: '3.8'

services:
  ocr-service:
    build: .
    container_name: ocr-service
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - city_service_network

networks:
  city_service_network:
    external: true
    name: city_service_network